monitor1:
    sources:
        - localhost_response:
            class: monitor.source.source_type.http.Http
            url: http://127.0.0.1:5000
        - pp_mischa_balance:
            class: monitor.source.source_type.PeerplaysBalance
            account_name: mischa
            symbol: TEST

    triggers:
        - RichUserTrigger:
            class: monitor.trigger.trigger_type.valuecompare.ValueCompare
            source: mischas_pp_balance
            greater: 99909
            level: 2

        - ErrorResponseCodeTrigger:
            class: monitor.trigger.trigger_type.valuecompare.ValueCompare
            source: localhost_response
            greater_or_equal: 300
            level: 2

        - ExpectedResponseCode:
            class: monitor.trigger.trigger_type.valuecompare.ValueCompare
            equal: 200
            level: 2

    actions:
        - action2:
            class: monitor.action.action_type.console.Console
            level: 2
