EventMonitor:
    sources:
        - wittnessProposals:
            class: http_status_code.HttpStatusCode
            url: https://www.blockchainprojectsbv.com/

    triggers:
        - TooLongInProgress:
            class: valuecompare.ValueCompare
            less: 300
            level: 2

    actions:
        - action:
            class: stdout.Stdout
            level: 2
