EventMonitor:
    sources:
        - wittnessProposals:
            class: http_status_code.HttpStatusCode
            url: https://www.blockchainprojectsbv.com/

    triggers:
        - 5TooLongInProgress:
            class: event_outdated.EventOutdated
            status: upcoming
            #explorer: http://95.216.13.245:8001/overview/event/{0}
            time_window: 900
            downtime: 600
            level: 2

        #4 is no real trigger
        - 3EventFinishedTooLong:
            class: event_outdated.EventOutdated
            status: finished
            #explorer: http://95.216.13.245:8001/overview/event/{0}
            time_window: 1800
            downtime: 600
            level: 2

        - 2EventInProgress:
            class: event_outdated.EventOutdated
            status: in-progress
            #explorer: http://95.216.13.245:8001/overview/event/{0}
            time_window: 18000
            downtime: 600
            level: 2

        - 1DuplicateEvents:
            class: duplicate_event.DuplicateEvent
            seperators: ".| . | @ | v |"
            time_window: 21600
            downtime: 600
            level: 2

    actions:
        - action:
            class: stdout.Stdout
            level: 2
