Http_and_Peerplays_Monitor:
    sources:
        - localhost_response:
            class: monitor.source.http.Http
            url: http://127.0.0.1:5000
        - localhost_response_two:
            class: monitor.source.http.Http
            url: http://127.0.0.1:5000



    triggers:
        - RichUserTrigger:
            class: monitor.trigger.valuecompare.ValueCompare
            source: localhost_response # Only use data retrieved from <source> to check this trigger
            greater: 99909
            level: 2

        - ErrorResponseCodeTrigger:
            class: monitor.trigger.valuecompare.ValueCompare
            greater_or_equal: 300
            level: 2

        - ExpectedResponseCode:
            class: monitor.trigger.valuecompare.ValueCompare
            equal: 200
            downtime: 5
            level: 2

    actions:
        - action2:
            class: monitor.action.console.Console
            level: 2
