Http_and_Peerplays_Monitor:
    sources:
        - localhost_response:
            class: monitor.source.peerplays_events.PeerplaysEvents

    triggers:
        - ErrorResponseCodeTrigger:
            class: monitor.trigger.valuecompare.ValueCompare
            greater_or_equal: 400
            downtime: 30
            level: 2

    actions:
        - action:
            class: monitor.action.stdout.Stdout
            level: 2

