Http_and_Peerplays_Monitor:
    sources:
        - wittnessProposals:
            class: monitor.source.http.Http
            url: http://blockchainprojectsbv.com
            account_name: mischa

    triggers:
        - TooLongInProgress:
            class: monitor.trigger.data_available.DataAvailable
            status: in_progress
            time_window: 7200
            downtime: 3600
            level: 2

    actions:
        - action:
            class: monitor.action.stdout.Stdout
            level: 2

