Http_and_Peerplays_Monitor:
    sources:
        - localhost_response:
            class: monitor.source.http.Http
            url: http://127.0.0.1:5000

    triggers:
        - ErrorResponseCodeTrigger:
            class: monitor.trigger.valuecompare.ValueCompare
            greater_or_equal: 400
            downtime: 3
            level: 2

    actions:
        - action:
            class: monitor.action.telegram.Telegram
            level: 2
