Http_and_Peerplays_Monitor:
    sources:
        - localhost_response:
            class: monitor.source.http.Http
            url: http://127.0.0.1:5000


    triggers:
        - RichUserTrigger:
            class: monitor.trigger.data_changed.DataChanged
            source: localhost_response # Only use data retrieved from <source> to check this trigger
            downtime: 7
            greater: 210
            level: 0


    actions:
        - action:
            class: monitor.action.stdout.Stdout
            level: 0
