Http_and_Peerplays_Monitor:
    sources:
        - CricketEvents:
            class: monitor.source.peerplays_events.PeerplaysEvents

    triggers:
        - TooLongInProgress:
            class: monitor.trigger.event_transition.EventTransition
            #status upcoming, inprogress
            time_window: 10
            #downtime: 100  # --> 100 seconds no trigger
            level: 2


    actions:
        - action:
            class: monitor.action.stdout.Stdout
            level: 2

