Http_and_Peerplays_Monitor:
    sources:
        - wittnessProposals:
            class: http_status_code.HttpStatusCode
            url: http://localhost:5000
            account_name: mischa

    triggers:
        - TooLongInProgress:
            class: data_available.DataAvailable
            status: in_progress
            time_window: 7200
            downtime: 10
            level: 2

    actions:
        - action:
            class: stdout.Stdout
            level: 2
