monitor:
    #Define the preprocessing source
    source:
        type: http
        url: http://127.0.0.1:5000/


    #Define the values to be monitored in the processing step and its triggers
    triggers:
        list:
            - trigger1: #TODO: is it useful to add logical disjunction ?
                type: value_compare
                "!=": 200
                group: 0 #All triggers are checked before they fire. If you define group, you can link two triggers
                level: 0 #Use level to map to console action, high levels indicate high priorities

            - trigger2:
                type: value_compare
                equal: 200
                level: 1


    #Define action to be executed in case the trigger is met
    actions:
        level-redundancy: True #If True all actions with a level smaller that than the
                               #triggerlevel will be executed as well (default=False)
        list:
            - action1:
                type: log
                level: 0

            - action2:
                type: console
                level: 1
