monitor:
    #Define the preprocessing source
    source:
        type: http
        address: http://localhost:5000/overview


    #Define the values to be monitored in the processing step and its triggers
    triggers:
        list:
            - trigger1:
                type: int_compare
                unequal: 200
                group: 0 #All triggers are checked before they fire. If you define group, you can link two triggers
                level: 0 #Use level to map to console action, high levels indicate high priorities

            - trigger2:
                type: int_compare
                greater: 300
                level: 1


    #Define action to be executed in case the trigger is met
    actions:
        level-redundancy: True #If True all action below the level will be executed as well
        list:
            - action1:
                type: log,
                level: 0

            - action2:
                type: console,
                level: 1
